config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  root 'topics#index'
  resources :topics, only: [:create,:destroy,:show]
  resources :comments, only: [:create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  validates_uniqueness_of :comment_id, scope: :user_id
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title, presence: true
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable,
         :omniauthable, omniauth_providers: [:twitter]
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
   def self.find_for_oauth(auth)
           user = User.where(uid: auth.uid, provider: auth.provider).first

           unless user
              user = User.create(
           uid:      auth.uid,
           provider: auth.provider,
           email:    User.dummy_email(auth),
           password: Devise.friendly_token[0, 20],
           image: auth.info.image,
           name: auth.info.name,
           username: auth.info.nickname,
           )

       end
      user.skip_confirmation!
   user
  end

  def already_liked?(comment)
    self.likes.exists?(comment_id: comment.id)
  end

  private

  def self.dummy_email(auth)
   "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
  before_action :define_topic
  before_action :configure_permitted_parameters, if: :devise_controller?


protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def define_topic
    @topic = Topic.new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in?, only: [:create]

  def create
      @comment = current_user.comments.build(comment_params)
      if @comment.save
        redirect_to topic_path(@comment.topic_id)
      else
        render 'topics/show'
      end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    redirect_to topic_url(@comment.topic_id)
    flash[:notice] = "コメントを削除しました"
  end

private
  def comment_params
      params.require(:comment).permit(:topic_id, :user_id, :content, :image)
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in?, only: [:create, :destroy]
  def create
    @like = current_user.likes.create(comment_id: params[:comment_id])
    redirect_back(fallback_location: topic_path(@like.comment.topic.id))
  end

  def destroy
    @likes = Likes.find_by(user_id: current_user.id, comment_id: params[:comment_id])
    @likes.destroy
    redirect_back(fallback_location: topic_path(@like.comment.topic.id))
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
   callback_from :twitter
 end

 private
 def callback_from(provider)
   provider = provider.to_s

   @user = User.find_for_oauth(request.env['omniauth.auth'])

   if @user.persisted?
     print("persisted true")
     flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
     sign_in_and_redirect @user, event: :authentication
   else
    redirect_to root_url
   end
 end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :logged_in?, only: [:create, :destroy]

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to root_url
    else
      redirect_to root_url
    end
  end

  def index
    @topics = Topic.all.page(params[:page])
    @topic = Topic.new
  end

  def destroy
      @topic = Topic.find_by(id: params[:id])
      @topic.destroy
      redirect_to root_url
  end

  def show
    @topic = Topic.find_by(id: params[:id])
    @comment = Comment.new
    @comments = @topic.comments
    @like = Like.new
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    unless  user_signed_in?
      flash[:alert] = "コメントするにはログインしてください"
      redirect_to new_user_session_url
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_header.html.erb
<header>
  <div class="logo">
    <a href="/">
    <i class="fas fa-volleyball-ball fa-2x"></i>
    </a>
    <h1>volley-info</h1>
  </div>
  <ul>
    <% if user_signed_in? %>
      <li><%= link_to current_user.name+"さん", edit_user_registration_path %></li>
      <li><%= link_to "TOPICS", root_url %></li>
    <% else %>
      <li><%= link_to 'SIGNUP', new_user_registration_path %></li>
      <li><%= link_to 'LOGIN', new_user_session_path %></li>
    <% end %>
  </ul>
</header>

app/views/layouts/_sidebar.html.erb

  <div class="sidebar">
   <div class="sidebar_item">
     <ul>
         <li><p>volley-infoは全国のバレーボールプレイヤーのための情報交換掲示板です</p></li>
         <% if user_signed_in? %>
    　　　　　<% if current_user.admin? %>
               <li><strong>管理者としてログインしています</strong></li>
               <%= form_for(@topic, url: topics_path, method: :post) do |f| %>
                 <%= f.label :title,"TOPICを作成する", class:"label-control" %>
                 <%= f.text_field :title, class: 'form-control' %>
                 <%= f.submit "作成する" %>
               <% end %>
             <% end %>
               <li><%= link_to "topics", root_url %></li>
               <li><%= link_to "profile", edit_user_registration_path %></li>
               <li><%= link_to "logout",destroy_user_session_path,data: { confirm: "本当にログアウトしますか?" }, method: :delete %></li>
            <% else %>
                <li><%= link_to 'signup', new_user_registration_path %></li>
                <li><%= link_to 'login', new_user_session_path %></li>
             <% end %>
    </ul>
   </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VolleyInfo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render partial: "layouts/sidebar" %>
      <div class="main-article">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    </div>
  </body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic, url: topics_path) do |f| %>
  <%= f.label :title, class:"label-control" %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.submit "作成", class: "btn btn-submit" %>
<% end %>

app/views/topics/index.html.erb
<h1>TOPIC一覧</h1>
<% if @topics.present? %>
<ul>
  <% @topics.each do |topic| %>
    <li><%= link_to topic.title,topic_path(topic) %>
      <p>コメント数:<%= topic.comments.count %></p>
      <% if user_signed_in? %>
  　　　<% if current_user.admin? %>
         <%= link_to "削除",topic_path(topic), method: :delete %>
         <% end %>
         <% end %>
       </li>
  <% end %>
</ul>
<%= paginate @topics %>
  <% end %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>
  <% @comments.each do |comment| %>
    <li>
      ユーザーID:<%= comment.user.id %>
      <h3><%= comment.user.name %></h3>
      <h3><%= comment.content %></h3>
      <h3>いいね件数:<%= comment.likes.count %></h3>
      <% if current_user.already_liked?(comment) %>
       <%= button_to 'いいね取り消し',comment_like_path(comment),method: :delete  %>
      <% else %>
       <%= button_to 'いいね', comment_likes_path(comment) %>
       <% end %>
      <% if current_user == comment.user %>
        <%= link_to "削除", comment_path(comment), method: :delete, data: { confirm: "本当に削除しますか?" } %>
      <% end %>
    </li>
  <% end %>

  <%= form_for(@comment, url: comments_path(@comment)) do |f| %>
    <%= f.text_field :content %>
    <%= f.hidden_field :topic_id, :value => @topic.id %>
    <%= f.submit "送信する" %>
  <% end %>